version: '3.9'

services:
  server:
    build:
      context: .
      dockerfile: cmd/server/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - FINNHUB_API_KEY=${FINNHUB_API_KEY}
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
    restart: on-failure
