version: '3.9'

services:
  investor:
    build:
      context: .
      dockerfile: investor/Dockerfile
    env_file:
      - .env
    ports:
      - "8080:8080"
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
    restart: on-failure
